version: '3.8'

services:
  # Servidor Python: API, WebSockets y Publicador MQTT
  python-sensor:
    build: .
    container_name: sensor_api_welltech
    ports:
      - "5000:5000"
    volumes:
      - ./script.py:/app/script.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - mqtt-broker

  # Broker MQTT (Mosquitto)
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt_welltech
    ports:
      - "1883:1883"
    volumes:
      # Mapeo directo al archivo de configuración que tienes en la carpeta mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf